---
title: 梯子多用户配置
categories:
- 技术
tags:
- 梯子
- linux

---
第一次是在ubantu下操作,版本18.4,内核版本4.15 比4.9高.
运行命令
``` lsmod |grep bbr ```
结果
``` 
root@vultr:~# lsmod |grep bbr
tcp_bbr                20480  5
```
说明已经开启bbr,不需要其他操作

---
然后安装ss
```
#：apt-get install python-pip
#：pip install shadowsocks
```
centos7安装pip用`yum install python-pip`

安装ss的时候报错
```
root@vultr:~# pip install shadowsocks
Collecting shadowsocks
  Downloading https://files.pythonhosted.org/packages/02/1e/e3a5135255d06813aca6631da31768d44f63692480af3a1621818008eb4a/shadowsocks-2.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Q7TlHV/shadowsocks/
```
(可能是python一些东西版本太低)
运行
```
sudo python -m pip install --upgrade --force pip 
sudo pip install setuptools==33.1.1
```
然后再安装ss,还是报错
```
root@vultr:~# pip install shadowsocks
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```
因为将pip更新后库里面的函数有所变动造成这个问题。 解决方法
```
sudo gedit /usr/bin/pip
将原来的：

from pip import main
if __name__ == '__main__':
    sys.exit(main())
    
改成：

from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())
```
gedit可以由vi代替,注意“--”和“-”的区别.
再安装就成功了.
顺便配一下多用户.
```
vi /etc/shadowsocks.json
```
然后编辑
```
{
"server": "0.0.0.0",
"port_password": {
"8381": "password1",
"8382": "password2",
"8383": "password3",
"8384": "password4"
},
"timeout": 300,
"method": "aes-256-cfb"
}
```
再启动服务```ssserver -c /etc/shadowsocks.json -d start```
报错:
```
AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: EVP_CIPHER_CTX_cleanup
```
google后,按照<https://blog.csdn.net/blackfrog_unique/article/details/60320737>大佬解释,这个问题是由于在openssl1.1.0版本中，废弃了EVP_CIPHER_CTX_cleanup函数.
```
修改方法：

用vim打开文件：vim /usr/local/lib/python2.7/dist-packages/shadowsocks/crypto/openssl.py (该路径请根据自己的系统情况自行修改，如果不知道该文件在哪里的话，可以使用find命令查找文件位置)
跳转到52行（shadowsocks2.8.2版本，其他版本搜索一下cleanup）
进入编辑模式
将第52行libcrypto.EVP_CIPHER_CTX_cleanup.argtypes = (c_void_p,) 
改为libcrypto.EVP_CIPHER_CTX_reset.argtypes = (c_void_p,)
再次搜索cleanup（全文件共2处，此处位于111行），将libcrypto.EVP_CIPHER_CTX_cleanup(self._ctx) 
改为libcrypto.EVP_CIPHER_CTX_reset(self._ctx)
保存并退出
启动shadowsocks服务：service shadowsocks start 或 sslocal -c ss配置文件目录
问题解决
```
之后```ssserver -c /etc/shadowsocks.json -d start```正常启动.


-------
2019-1-25
 今天又来配置了一遍ss,配置文件如下
  ```
 {
"server":"0.0.0.0",
"password":{
"8381":"password1",
"8382":"password2",
"8383":"password3",
"8384":"password4"
},
"timeout":"300",
"method":"aes-256-cfb"
}
 ```
 运行```ssserver -c /etc/shadowsocks.json -d start```时,报错
 ````
 [root@vultr shadowsocks]# ssserver -c /etc/shadowsocks.json
INFO: loading config from /etc/shadowsocks.json
Traceback (most recent call last):
  File "/usr/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/lib/python2.7/site-packages/shadowsocks/server.py", line 34, in main
    config = shell.get_config(False)
  File "/usr/lib/python2.7/site-packages/shadowsocks/shell.py", line 262, in get_config
    check_config(config, is_local)
  File "/usr/lib/python2.7/site-packages/shadowsocks/shell.py", line 124, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/usr/lib/python2.7/site-packages/shadowsocks/encrypt.py", line 44, in try_cipher
    Encryptor(key, method)
  File "/usr/lib/python2.7/site-packages/shadowsocks/encrypt.py", line 83, in __init__
    random_string(self._method_info[1]))
  File "/usr/lib/python2.7/site-packages/shadowsocks/encrypt.py", line 100, in get_cipher
    key, iv_ = EVP_BytesToKey(password, m[0], m[1])
  File "/usr/lib/python2.7/site-packages/shadowsocks/encrypt.py", line 61, in EVP_BytesToKey
    md5.update(data)
TypeError: must be string or buffer, not dict
 ````
 网上找了半天,没有找到类似错误的.最后只能自己分析.
 TypeError说明是类型错误,最下面报错的地方是
 ``` File "/usr/lib/python2.7/site-packages/shadowsocks/encrypt.py", line 61, in EVP_BytesToKey
    md5.update(data)```
去了文件的第61行一看
```
 while len(b''.join(m)) < (key_len + iv_len):
     57         md5 = hashlib.md5()
     58         data = password
     59         if i > 0:
     60             data = m[i - 1] + password
     61         md5.update(data)
     62         m.append(md5.digest())
     63         i += 1
```
应该是穿入password错误,不应该是dict.但是我配置的是多用户,有多个端口和对应的密码,只能传dict.再一看配置文件,原来多用户需要将"password"改为"port_password".


之后运行```ssserver -c /etc/shadowsocks.json```
还是报
```AttributeError: /lib64/libcrypto.so.10: undefined symbol: EVP_CIPHER_CTX_reset```
根据openssl官网https://www.openssl.org/docs/man1.1.0/crypto/EVP_CIPHER_CTX_reset.html
的说法,EVP_CIPHER_CTX was made opaque in OpenSSL 1.1.0. As a result, EVP_CIPHER_CTX_reset() appeared and EVP_CIPHER_CTX_cleanup() disappeared. EVP_CIPHER_CTX_init() remains as an alias for EVP_CIPHER_CTX_reset().
用reset替代了cleanup,我之前也换了啊.最后,只能尝试一下,用reset的别名init替代,最后运行成功了!  ???

```
[root@vultr shadowsocks]# vi /usr/lib/python2.7/site-packages/shadowsocks/crypto/openssl.py
[root@vultr shadowsocks]# ssserver -c /etc/shadowsocks.json
INFO: loading config from /etc/shadowsocks.json
2019-01-25 07:40:11 INFO     loading libcrypto from libcrypto.so.10
2019-01-25 07:40:11 INFO     starting server at 0.0.0.0:8384
2019-01-25 07:40:11 INFO     starting server at 0.0.0.0:8383
2019-01-25 07:40:11 INFO     starting server at 0.0.0.0:8382
2019-01-25 07:40:11 INFO     starting server at 0.0.0.0:8381
```

然后配置自启动
```
vim /etc/systemd/system/shadowsocks.service
```
内容如下
```
[Unit]
Description=Shadowsocks

[Service]
TimeoutStartSec=0
ExecStart=/usr/bin/ssserver -c /etc/shadowsocks.json

[Install]
WantedBy=multi-user.target
```
然后运行这三个命令:
```
[root@vultr shadowsocks]# systemctl enable shadowsocks
Created symlink from /etc/systemd/system/multi-user.target.wants/shadowsocks.service to /etc/systemd/system/shadowsocks.service.
[root@vultr shadowsocks]# systemctl start shadowsocks
[root@vultr shadowsocks]# systemctl status shadowsocks -l
 shadowsocks.service
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-01-25 08:14:35 UTC; 3min 22s ago
 Main PID: 4264 (ssserver)
   CGroup: /system.slice/shadowsocks.service
           └─4264 /usr/bin/python2 /usr/bin/ssserver -c /etc/shadowsocks.json
```
状态是active说明启动成功

然后关闭防火墙
```systemctl stop firewalld```
查看日志
```
[root@vultr bin]# journalctl -u shadowsocks.service -f
-- Logs begin at Fri 2019-01-25 06:19:58 UTC. --
Jan 25 08:14:36 vultr.guest ssserver[4264]: 2019-01-25 08:14:36 INFO     starting server at 0.0.0.0:8381
Jan 25 08:22:56 vultr.guest systemd[1]: Stopping shadowsocks.service...
Jan 25 08:22:56 vultr.guest systemd[1]: Stopped shadowsocks.service.
Jan 25 08:23:06 vultr.guest systemd[1]: Started shadowsocks.service.
Jan 25 08:23:06 vultr.guest ssserver[4301]: INFO: loading config from /etc/shadowsocks.json
Jan 25 08:23:06 vultr.guest ssserver[4301]: 2019-01-25 08:23:06 INFO     loading libcrypto from libcrypto.so.10
Jan 25 08:23:06 vultr.guest ssserver[4301]: 2019-01-25 08:23:06 INFO     starting server at 0.0.0.0:8384
Jan 25 08:23:06 vultr.guest ssserver[4301]: 2019-01-25 08:23:06 INFO     starting server at 0.0.0.0:8383
Jan 25 08:23:06 vultr.guest ssserver[4301]: 2019-01-25 08:23:06 INFO     starting server at 0.0.0.0:8382
Jan 25 08:23:06 vultr.guest ssserver[4301]: 2019-01-25 08:23:06 INFO     starting server at 0.0.0.0:8381
```
手机移动网一直连不上不知道什么情况
公司网就可以.

不翻墙只能连新加坡服务器
